- name: provision rot13 webapp and infra
  hosts: localhost
  become: yes
  become_user: root
  roles:
#    - base
    - nginx
    - postgres
    - doublerot13
  vars:
    - db_name: doublerot13
    - db_user: doublerot13
    - db_password: SuperSafePassword
    - update_apt_cache: yes
