---




- name: create systemd entry
  template src=templates/doublerot13.j2 dest=/etc/systemd/system/doublerot13.service

- name: update app
  git: repo=https://github.com/ngamber/doublerot13 dest=/var/www/doublerot13
  notify: restart doublerot13

- name: start app
  service: name=doublerot13 state=started enabled=yes
